/*CREAR TABLA DE VACANTES*/
CREATE TABLE VACANTES(
ID INT NOT NULL PRIMARY KEY,
PUESTO VARCHAR(50) NOT NULL,
STATUS ENUM('publicacion','seleccion','entrevistas','contratacion'),
CANDIDATOS INT NOT NULL,
VACANTES INT NOT NULL
);

/*CREAR VACANTES*/
INSERT INTO VACANTES
VALUES(0,'PROGRAMADOR JAVA','publicacion',0,30);

INSERT INTO VACANTES
VALUES(2,'PROGRAMADOR PHYTON','publicacion',0,2);

/*CAMBIAR UN VALOR EN UN FILA*/
UPDATE VACANTES
SET ID = 1
WHERE ID = 0;

